<?php
echo "Количество секунд в часе равно:";
echo "<br>";
$secondsInAnHour = 1 * (60 * 60);
echo "В одном часе 60 минут, в одной минуте 60 секунд, итого 1 * (60 * 60) = $secondsInAnHour секуд";
$a = 10;
$b = 2;
echo 'Данны переменные $a=10, $b=2. Выведем их :';
echo "<br>";
echo 'Сумму: $a + $b = ' . ($a + $b);
echo "<br>";
echo 'Разность: $a - $b =' . ($a - $b);
echo "<br>";
echo 'Деление: $a / $b =' . ($a / $b);
echo "<br>";
echo 'Умножение: $a * $b =' . ($a * $b);
echo 'Данны переменные  $a=19, $b=2.Просумируем и  выведем их в отельной перемнной $rezult:';
$a = 19;
$b = 2;
echo "<br>";
$rezult = $a + $b;
echo '$rezult = ' . $rezult;